### ISSUE TITLE
⚡️ Enketo seeking new maintainers ⚡️

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo#1316]
Since 2021, Enketo has been primarily maintained by the [ODK team](https://getodk.org/about/team.html). Prior to that, it was maintained by its creator, Martijn, supported by funding and guidance from [a range of organizations](https://github.com/enketo/enketo/tree/main/packages/enketo-express#funding).

The ODK team will be stepping down as primary maintainers at the end of 2024. We are currently seeking individuals and organizations to ensure continued support of Enketo. If you are interested in being part of Enketo’s next chapter, please share a little bit about your availability and ideas for the platform in the comments.

When the ODK team started exploring taking on Enketo maintenance, we started by doing code review and taking on increasingly challenging development tasks until we were ready to have commit access. At this time, we also convened other organizations relying on Enketo to understand their needs. We are imagining a similar transition now but are also open to alternative process suggestions.

**Comment by tinok** [comment]
Thanks for posting this and for all the maintenance done over the last years. As previously discussed with @yanokwa, we at Kobo certainly can and want to take maintenance over from getODK later this year. 

As you know, we worked closely with Martijn since 2014 to make Enketo a fully open source project and to create Enketo Express, as well as to cover most bug fixes and maintenance until around 2019. So we are absolutely delighted to take up this role again.

**Comment by svadla-oc** [comment]
Thank you ODK for all the work you have done as maintainers of Enketo!
@tinok thank you for your willingness to take over Enketo maintenance. OpenClinica team is committed to continuing our support and contributions to Enketo development. We look forward to working with you as you take over maintenance from ODK!

**Comment by lognaturel** [comment]
Closing as @tinok and team ramp up to take on this role!
